#server:
#  port: 8005
#
#spring:
#  application:
#    name: gateway-server # 应用名
#    redis:
#      host: localhost # Redis服务器地址
#      port: 6379 # Redis服务器连接端口
#      # Redis服务器连接密码（默认为空），注释放到上面来，不然控制台可能会一直打印日志
#      password:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 # 注册中心地址
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: blog-article
##          uri: http://127.0.0.1:8001
#          uri: lb://article-server
#          predicates:
#            - Path=/article/**
#          filters:
#            #移除前缀/article
##            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器bean名
#                key-resolver: '#{@uriKeyResolver}'
#                # 期望用户每秒请求数，gateway令牌桶填充速率
#                redis-rate-limiter.replenishRate: 2
#                # 允许用户每秒最大访问数，令牌桶最大令牌数
#                redis-rate-limiter.burstCapacity: 4
#
#        - id: blog-question
##          uri: http://127.0.0.1:8002
#          uri: lb://question-server
#          predicates:
#            - Path=/question/**
#          filters:
#          #移除前缀/question
##            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器bean名
#                key-resolver: '#{@uriKeyResolver}'
#                # 期望用户每秒请求数，gateway令牌桶填充速率
#                redis-rate-limiter.replenishRate: 2
#                # 允许用户每秒最大访问数，令牌桶最大令牌数
#                redis-rate-limiter.burstCapacity: 4
#
#        - id: blog-system
##          uri: http://127.0.0.1:8003
#          uri: lb://system-server
#          predicates:
#            - Path=/system/**
#          filters:
#          #移除前缀/system
##            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器bean名
#                key-resolver: '#{@uriKeyResolver}'
#                # 期望用户每秒请求数，gateway令牌桶填充速率
#                redis-rate-limiter.replenishRate: 2
#                # 允许用户每秒最大访问数，令牌桶最大令牌数
#                redis-rate-limiter.burstCapacity: 4
#
#        - id: auth-system
##          uri: http://127.0.0.1:8004
#          uri: lb://auth-server
#          predicates:
#            - Path=/auth/**
#          filters:
#          #移除前缀/auth
##            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                # 限流过滤器bean名
#                key-resolver: '#{@uriKeyResolver}'
#                # 期望用户每秒请求数，gateway令牌桶填充速率
#                redis-rate-limiter.replenishRate: 2
#                # 允许用户每秒最大访问数，令牌桶最大令牌数
#                redis-rate-limiter.burstCapacity: 4