CREATE DATABASE IF NOT EXISTS blog_article DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS blog_question DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS blog_auth DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS blog_system DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS nacos DEFAULT CHARACTER SET utf8mb4;